language: python
python:
 - "2.6"
 - "2.7"
# command to install build dependencies
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq pep8
# command to install dependencies
install:
 - pip install -r requirements.txt
# command to run tests
script:
 - make test
 - make translate-all
